### PR TITLE
Run BMv2 PTF tests with docker-compose

### PR DESCRIPTION
**Pull request by daniele-moro**

### CODE REVIEW

**Comment by ccascone** [comment]
As I commented to you on Slack, I'm starting to think we should not use docker compose here. I see the benefits of separating the containers, i.e., swap the device under test (e.g. a new version of stratum_bmv2) without rebuilding the docker image for the tester. However, the fact that you have to do `command: "tail -f /dev/null"` in `docker-compose.yml`, and the retry logic in #68  looks like a red flag. If what you need to do is orchestrate the execution of the different containers, then it would be easier to have a bash script such as the existing `docker_run.sh` to run the two containers in order, and terminate/remove them when the test is done. What do you think?

**Comment by daniele-moro** [comment]
Yes, the 2 approaches (docker-compose or bash script with separated containers) are equivalent in this case.
The advantage I see in using docker-compose is that the services are defined in a well-structured YAML file rather than being embedded into a bash script.

**Comment by ccascone** [comment]
I think it would be better to have a bit more complexity in the form of a bash script that imperatively starts and stops each container in the right order, rather than shoehorning docker-compose into doing something that was not designed for. I don't think the YAML benefits justify the added complexity of #68.

**Comment by ccascone** [comment]
This script does a similar thing but only with one container: https://github.com/opennetworkinglab/ngsdn-tutorial/blob/master/ptf/run_tests

**Comment by daniele-moro** [comment]
Yes, I'll modify it as a bash script. My only concern is related to the sleep in between the 2 containers (that was the reason to introduce #68 ). Do you think it could be an issue?

**Comment by ccascone** [comment]
As long as we find a value that works reliably on Travis VMs, we should be good

**Comment by daniele-moro** [comment]
Pushed the bash script on #71.

**Comment by ccascone** [comment]
Ok, closing this

**Pull request closed without merging**
